# docker-compose Cassandra Test Cluster
# docker-compose rm
# docker-compose up
# docker run -it --link cassandra_cassandra-1_1:cassandra --rm cassandra cqlsh cassandra
# copy paste the test script on cassandra-1
# run select on cassandra-2
#

version: "3"

services:
  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra:3.11.0
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    # networks:
    #   - dc1ring

  cassandra-1:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
    depends_on:
      - "cassandra-seed"
    # networks:
    #   - dc1ring

  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
  cassandra-2:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
    depends_on:
      - "cassandra-seed"
    # networks:
    #   - dc1ring

  docker-go:
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - cassandra-seed:cassandra
    ports:
      - "8080:8080"
    depends_on:
      - cassandra-seed
    environment:
      CASSANDRA_URL: cassandra:9042
    # networks: 
    #   - dc1ring

  portainer:
    image: portainer/portainer
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
      # Enable you to access potainers web interface from your host machine
      # using http://localhost:10001
    ports:
      - "10001:9000"
    
  logspout:
    build: logspout
    # command: syslog+tcp://logs.papertrailapp.com:$PAPERTRAIL_PORT
    env_file:
      - logspout/logspout.env
    restart: always
    ports:
      - "8000:80"
    volumes:
      # security concern:
      # https://raesene.github.io/blog/2016/03/06/The-Dangers-Of-Docker.sock/
      # http://stackoverflow.com/questions/40844197
      - /var/run/docker.sock:/var/run/docker.sock:ro

# networks:
#   dc1ring:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.0.0/16

  

  

