# docker-compose Cassandra Test Cluster
# docker-compose rm
# docker-compose up
# docker run -it --link cassandra_cassandra-1_1:cassandra --rm cassandra cqlsh cassandra
# copy paste the test script on cassandra-1
# run select on cassandra-2
#

version: "2"

services:
  cassandra-1:
    hostname: cassandra-1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
       - ./data/cassandra-1:/var/lib/cassandra:rw
    ports:
      - "9042:9042"

  cassandra-2:
    hostname: cassandra-2
    image: cassandra:latest
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    links:
      - cassandra-1
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      - ./data/cassandra-2:/var/lib/cassandra:rw

  docker-go:
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - cassandra-1:cassandra
    ports:
      - "8080:8080"
    environment:
      CASSANDRA_URL: cassandra:9042

  

  

